//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 10:36:44 PM CET 
//


package it.polito.dp2.NFFG.sol3.service.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{https://france193.wordpress.com}r_policy"/>
 *         &lt;element ref="{https://france193.wordpress.com}t_policy"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rPolicy",
    "tPolicy"
})
@XmlRootElement(name = "policy")
public class Policy {

    @XmlElement(name = "r_policy")
    protected RPolicyType rPolicy;
    @XmlElement(name = "t_policy")
    protected TPolicyType tPolicy;

    /**
     * Gets the value of the rPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link RPolicyType }
     *     
     */
    public RPolicyType getRPolicy() {
        return rPolicy;
    }

    /**
     * Sets the value of the rPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link RPolicyType }
     *     
     */
    public void setRPolicy(RPolicyType value) {
        this.rPolicy = value;
    }

    /**
     * Gets the value of the tPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link TPolicyType }
     *     
     */
    public TPolicyType getTPolicy() {
        return tPolicy;
    }

    /**
     * Sets the value of the tPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPolicyType }
     *     
     */
    public void setTPolicy(TPolicyType value) {
        this.tPolicy = value;
    }

}
