//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 05:00:39 PM CET 
//


package it.polito.dp2.NFFG.sol3.models;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.NFFG.sol3.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TPolicy_QNAME = new QName("https://france193.wordpress.com", "t_policy");
    private final static QName _RPolicy_QNAME = new QName("https://france193.wordpress.com", "r_policy");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.NFFG.sol3.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VResults }
     * 
     */
    public VResults createVResults() {
        return new VResults();
    }

    /**
     * Create an instance of {@link PolicyType }
     * 
     */
    public PolicyType createPolicyType() {
        return new PolicyType();
    }

    /**
     * Create an instance of {@link TPolicyType }
     * 
     */
    public TPolicyType createTPolicyType() {
        return new TPolicyType();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link Nodes }
     * 
     */
    public Nodes createNodes() {
        return new Nodes();
    }

    /**
     * Create an instance of {@link Nffgs }
     * 
     */
    public Nffgs createNffgs() {
        return new Nffgs();
    }

    /**
     * Create an instance of {@link Nffg }
     * 
     */
    public Nffg createNffg() {
        return new Nffg();
    }

    /**
     * Create an instance of {@link NodesType }
     * 
     */
    public NodesType createNodesType() {
        return new NodesType();
    }

    /**
     * Create an instance of {@link LinksType }
     * 
     */
    public LinksType createLinksType() {
        return new LinksType();
    }

    /**
     * Create an instance of {@link PoliciesType }
     * 
     */
    public PoliciesType createPoliciesType() {
        return new PoliciesType();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Policies }
     * 
     */
    public Policies createPolicies() {
        return new Policies();
    }

    /**
     * Create an instance of {@link RPolicyType }
     * 
     */
    public RPolicyType createRPolicyType() {
        return new RPolicyType();
    }

    /**
     * Create an instance of {@link Links }
     * 
     */
    public Links createLinks() {
        return new Links();
    }

    /**
     * Create an instance of {@link VResults.VResult }
     * 
     */
    public VResults.VResult createVResultsVResult() {
        return new VResults.VResult();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicy() {
        return new Policy();
    }

    /**
     * Create an instance of {@link PolicyType.VResult }
     * 
     */
    public PolicyType.VResult createPolicyTypeVResult() {
        return new PolicyType.VResult();
    }

    /**
     * Create an instance of {@link TPolicyType.TraversalRequestedNode }
     * 
     */
    public TPolicyType.TraversalRequestedNode createTPolicyTypeTraversalRequestedNode() {
        return new TPolicyType.TraversalRequestedNode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPolicyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://france193.wordpress.com", name = "t_policy")
    public JAXBElement<TPolicyType> createTPolicy(TPolicyType value) {
        return new JAXBElement<TPolicyType>(_TPolicy_QNAME, TPolicyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RPolicyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://france193.wordpress.com", name = "r_policy")
    public JAXBElement<RPolicyType> createRPolicy(RPolicyType value) {
        return new JAXBElement<RPolicyType>(_RPolicy_QNAME, RPolicyType.class, null, value);
    }

}
