//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.12 at 04:31:54 PM CET 
//


package it.polito.dp2.NFFG.sol3.models;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.NFFG.sol3.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Node_QNAME = new QName("https://france193.wordpress.com", "node");
    private final static QName _Nodes_QNAME = new QName("https://france193.wordpress.com", "nodes");
    private final static QName _Nffgs_QNAME = new QName("https://france193.wordpress.com", "nffgs");
    private final static QName _Link_QNAME = new QName("https://france193.wordpress.com", "link");
    private final static QName _TPolicy_QNAME = new QName("https://france193.wordpress.com", "t_policy");
    private final static QName _Policies_QNAME = new QName("https://france193.wordpress.com", "policies");
    private final static QName _VResults_QNAME = new QName("https://france193.wordpress.com", "v_results");
    private final static QName _Nffg_QNAME = new QName("https://france193.wordpress.com", "nffg");
    private final static QName _Links_QNAME = new QName("https://france193.wordpress.com", "links");
    private final static QName _RPolicy_QNAME = new QName("https://france193.wordpress.com", "r_policy");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.NFFG.sol3.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PolicyType }
     * 
     */
    public PolicyType createPolicyType() {
        return new PolicyType();
    }

    /**
     * Create an instance of {@link VResultsType }
     * 
     */
    public VResultsType createVResultsType() {
        return new VResultsType();
    }

    /**
     * Create an instance of {@link TPolicyType }
     * 
     */
    public TPolicyType createTPolicyType() {
        return new TPolicyType();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link NodesType }
     * 
     */
    public NodesType createNodesType() {
        return new NodesType();
    }

    /**
     * Create an instance of {@link NffgsType }
     * 
     */
    public NffgsType createNffgsType() {
        return new NffgsType();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link PoliciesType }
     * 
     */
    public PoliciesType createPoliciesType() {
        return new PoliciesType();
    }

    /**
     * Create an instance of {@link NffgType }
     * 
     */
    public NffgType createNffgType() {
        return new NffgType();
    }

    /**
     * Create an instance of {@link LinksType }
     * 
     */
    public LinksType createLinksType() {
        return new LinksType();
    }

    /**
     * Create an instance of {@link RPolicyType }
     * 
     */
    public RPolicyType createRPolicyType() {
        return new RPolicyType();
    }

    /**
     * Create an instance of {@link PolicyType.VResult }
     * 
     */
    public PolicyType.VResult createPolicyTypeVResult() {
        return new PolicyType.VResult();
    }

    /**
     * Create an instance of {@link VResultsType.VResult }
     * 
     */
    public VResultsType.VResult createVResultsTypeVResult() {
        return new VResultsType.VResult();
    }

    /**
     * Create an instance of {@link TPolicyType.TraversalRequestedNode }
     * 
     */
    public TPolicyType.TraversalRequestedNode createTPolicyTypeTraversalRequestedNode() {
        return new TPolicyType.TraversalRequestedNode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://france193.wordpress.com", name = "node")
    public JAXBElement<NodeType> createNode(NodeType value) {
        return new JAXBElement<NodeType>(_Node_QNAME, NodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://france193.wordpress.com", name = "nodes")
    public JAXBElement<NodesType> createNodes(NodesType value) {
        return new JAXBElement<NodesType>(_Nodes_QNAME, NodesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NffgsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://france193.wordpress.com", name = "nffgs")
    public JAXBElement<NffgsType> createNffgs(NffgsType value) {
        return new JAXBElement<NffgsType>(_Nffgs_QNAME, NffgsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://france193.wordpress.com", name = "link")
    public JAXBElement<LinkType> createLink(LinkType value) {
        return new JAXBElement<LinkType>(_Link_QNAME, LinkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPolicyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://france193.wordpress.com", name = "t_policy")
    public JAXBElement<TPolicyType> createTPolicy(TPolicyType value) {
        return new JAXBElement<TPolicyType>(_TPolicy_QNAME, TPolicyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PoliciesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://france193.wordpress.com", name = "policies")
    public JAXBElement<PoliciesType> createPolicies(PoliciesType value) {
        return new JAXBElement<PoliciesType>(_Policies_QNAME, PoliciesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VResultsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://france193.wordpress.com", name = "v_results")
    public JAXBElement<VResultsType> createVResults(VResultsType value) {
        return new JAXBElement<VResultsType>(_VResults_QNAME, VResultsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NffgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://france193.wordpress.com", name = "nffg")
    public JAXBElement<NffgType> createNffg(NffgType value) {
        return new JAXBElement<NffgType>(_Nffg_QNAME, NffgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinksType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://france193.wordpress.com", name = "links")
    public JAXBElement<LinksType> createLinks(LinksType value) {
        return new JAXBElement<LinksType>(_Links_QNAME, LinksType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RPolicyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://france193.wordpress.com", name = "r_policy")
    public JAXBElement<RPolicyType> createRPolicy(RPolicyType value) {
        return new JAXBElement<RPolicyType>(_RPolicy_QNAME, RPolicyType.class, null, value);
    }

}
