//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.15 at 12:54:52 AM CET 
//


package it.polito.dp2.NFFG.sol3.service.models.NffgService;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="v_result" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="policy" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="result" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="traversal_requested_node" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="functional_type" use="required" type="{https://france193.wordpress.com}nodeFunctionalType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nffg" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="isPositive" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="source_node" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="destination_node" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vResult",
    "traversalRequestedNode"
})
@XmlRootElement(name = "FLPolicy")
public class FLPolicy {

    @XmlElement(name = "v_result")
    protected FLPolicy.VResult vResult;
    @XmlElement(name = "traversal_requested_node")
    protected List<FLPolicy.TraversalRequestedNode> traversalRequestedNode;
    @XmlAttribute(name = "id", required = true)
    protected long id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "nffg", required = true)
    protected long nffg;
    @XmlAttribute(name = "isPositive", required = true)
    protected boolean isPositive;
    @XmlAttribute(name = "source_node", required = true)
    protected long sourceNode;
    @XmlAttribute(name = "destination_node", required = true)
    protected long destinationNode;

    /**
     * Gets the value of the vResult property.
     * 
     * @return
     *     possible object is
     *     {@link FLPolicy.VResult }
     *     
     */
    public FLPolicy.VResult getVResult() {
        return vResult;
    }

    /**
     * Sets the value of the vResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLPolicy.VResult }
     *     
     */
    public void setVResult(FLPolicy.VResult value) {
        this.vResult = value;
    }

    /**
     * Gets the value of the traversalRequestedNode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the traversalRequestedNode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTraversalRequestedNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FLPolicy.TraversalRequestedNode }
     * 
     * 
     */
    public List<FLPolicy.TraversalRequestedNode> getTraversalRequestedNode() {
        if (traversalRequestedNode == null) {
            traversalRequestedNode = new ArrayList<FLPolicy.TraversalRequestedNode>();
        }
        return this.traversalRequestedNode;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nffg property.
     * 
     */
    public long getNffg() {
        return nffg;
    }

    /**
     * Sets the value of the nffg property.
     * 
     */
    public void setNffg(long value) {
        this.nffg = value;
    }

    /**
     * Gets the value of the isPositive property.
     * 
     */
    public boolean isIsPositive() {
        return isPositive;
    }

    /**
     * Sets the value of the isPositive property.
     * 
     */
    public void setIsPositive(boolean value) {
        this.isPositive = value;
    }

    /**
     * Gets the value of the sourceNode property.
     * 
     */
    public long getSourceNode() {
        return sourceNode;
    }

    /**
     * Sets the value of the sourceNode property.
     * 
     */
    public void setSourceNode(long value) {
        this.sourceNode = value;
    }

    /**
     * Gets the value of the destinationNode property.
     * 
     */
    public long getDestinationNode() {
        return destinationNode;
    }

    /**
     * Sets the value of the destinationNode property.
     * 
     */
    public void setDestinationNode(long value) {
        this.destinationNode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="functional_type" use="required" type="{https://france193.wordpress.com}nodeFunctionalType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class TraversalRequestedNode {

        @XmlAttribute(name = "functional_type", required = true)
        protected NodeFunctionalType functionalType;

        /**
         * Gets the value of the functionalType property.
         * 
         * @return
         *     possible object is
         *     {@link NodeFunctionalType }
         *     
         */
        public NodeFunctionalType getFunctionalType() {
            return functionalType;
        }

        /**
         * Sets the value of the functionalType property.
         * 
         * @param value
         *     allowed object is
         *     {@link NodeFunctionalType }
         *     
         */
        public void setFunctionalType(NodeFunctionalType value) {
            this.functionalType = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="policy" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="result" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class VResult {

        @XmlAttribute(name = "policy", required = true)
        protected long policy;
        @XmlAttribute(name = "result")
        protected Boolean result;
        @XmlAttribute(name = "time")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar time;
        @XmlAttribute(name = "message")
        protected String message;

        /**
         * Gets the value of the policy property.
         * 
         */
        public long getPolicy() {
            return policy;
        }

        /**
         * Sets the value of the policy property.
         * 
         */
        public void setPolicy(long value) {
            this.policy = value;
        }

        /**
         * Gets the value of the result property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isResult() {
            return result;
        }

        /**
         * Sets the value of the result property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setResult(Boolean value) {
            this.result = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTime(XMLGregorianCalendar value) {
            this.time = value;
        }

        /**
         * Gets the value of the message property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessage() {
            return message;
        }

        /**
         * Sets the value of the message property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessage(String value) {
            this.message = value;
        }

    }

}
