//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.13 at 07:46:32 PM CET 
//


package it.polito.dp2.NFFG.sol3.service.models.NffgService;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.NFFG.sol3.service.models.NffgService package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TPolicy_QNAME = new QName("https://france193.wordpress.com", "t_policy");
    private final static QName _RPolicy_QNAME = new QName("https://france193.wordpress.com", "r_policy");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.NFFG.sol3.service.models.NffgService
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FLVResults }
     * 
     */
    public FLVResults createFLVResults() {
        return new FLVResults();
    }

    /**
     * Create an instance of {@link PolicyType }
     * 
     */
    public PolicyType createPolicyType() {
        return new PolicyType();
    }

    /**
     * Create an instance of {@link TPolicyType }
     * 
     */
    public TPolicyType createTPolicyType() {
        return new TPolicyType();
    }

    /**
     * Create an instance of {@link FLLink }
     * 
     */
    public FLLink createFLLink() {
        return new FLLink();
    }

    /**
     * Create an instance of {@link FLPolicy }
     * 
     */
    public FLPolicy createFLPolicy() {
        return new FLPolicy();
    }

    /**
     * Create an instance of {@link RPolicyType }
     * 
     */
    public RPolicyType createRPolicyType() {
        return new RPolicyType();
    }

    /**
     * Create an instance of {@link FLLinks }
     * 
     */
    public FLLinks createFLLinks() {
        return new FLLinks();
    }

    /**
     * Create an instance of {@link FLNffg }
     * 
     */
    public FLNffg createFLNffg() {
        return new FLNffg();
    }

    /**
     * Create an instance of {@link NodesType }
     * 
     */
    public NodesType createNodesType() {
        return new NodesType();
    }

    /**
     * Create an instance of {@link LinksType }
     * 
     */
    public LinksType createLinksType() {
        return new LinksType();
    }

    /**
     * Create an instance of {@link PoliciesType }
     * 
     */
    public PoliciesType createPoliciesType() {
        return new PoliciesType();
    }

    /**
     * Create an instance of {@link FLNodes }
     * 
     */
    public FLNodes createFLNodes() {
        return new FLNodes();
    }

    /**
     * Create an instance of {@link FLNode }
     * 
     */
    public FLNode createFLNode() {
        return new FLNode();
    }

    /**
     * Create an instance of {@link FLVResults.VResult }
     * 
     */
    public FLVResults.VResult createFLVResultsVResult() {
        return new FLVResults.VResult();
    }

    /**
     * Create an instance of {@link FLNffgs }
     * 
     */
    public FLNffgs createFLNffgs() {
        return new FLNffgs();
    }

    /**
     * Create an instance of {@link FLPolicies }
     * 
     */
    public FLPolicies createFLPolicies() {
        return new FLPolicies();
    }

    /**
     * Create an instance of {@link PolicyType.VResult }
     * 
     */
    public PolicyType.VResult createPolicyTypeVResult() {
        return new PolicyType.VResult();
    }

    /**
     * Create an instance of {@link TPolicyType.TraversalRequestedNode }
     * 
     */
    public TPolicyType.TraversalRequestedNode createTPolicyTypeTraversalRequestedNode() {
        return new TPolicyType.TraversalRequestedNode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPolicyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://france193.wordpress.com", name = "t_policy")
    public JAXBElement<TPolicyType> createTPolicy(TPolicyType value) {
        return new JAXBElement<TPolicyType>(_TPolicy_QNAME, TPolicyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RPolicyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://france193.wordpress.com", name = "r_policy")
    public JAXBElement<RPolicyType> createRPolicy(RPolicyType value) {
        return new JAXBElement<RPolicyType>(_RPolicy_QNAME, RPolicyType.class, null, value);
    }

}
