//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.15 at 09:03:22 PM CET 
//


package it.polito.dp2.NFFG.sol3.service.models.NffgService;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.NFFG.sol3.service.models.NffgService package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.NFFG.sol3.service.models.NffgService
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FLPolicy }
     * 
     */
    public FLPolicy createFLPolicy() {
        return new FLPolicy();
    }

    /**
     * Create an instance of {@link FLVResults }
     * 
     */
    public FLVResults createFLVResults() {
        return new FLVResults();
    }

    /**
     * Create an instance of {@link FLLink }
     * 
     */
    public FLLink createFLLink() {
        return new FLLink();
    }

    /**
     * Create an instance of {@link FLPolicy.FLVResult }
     * 
     */
    public FLPolicy.FLVResult createFLPolicyFLVResult() {
        return new FLPolicy.FLVResult();
    }

    /**
     * Create an instance of {@link FLPolicy.FLTraversalRequestedNode }
     * 
     */
    public FLPolicy.FLTraversalRequestedNode createFLPolicyFLTraversalRequestedNode() {
        return new FLPolicy.FLTraversalRequestedNode();
    }

    /**
     * Create an instance of {@link FLLinks }
     * 
     */
    public FLLinks createFLLinks() {
        return new FLLinks();
    }

    /**
     * Create an instance of {@link FLNffg }
     * 
     */
    public FLNffg createFLNffg() {
        return new FLNffg();
    }

    /**
     * Create an instance of {@link FLNode }
     * 
     */
    public FLNode createFLNode() {
        return new FLNode();
    }

    /**
     * Create an instance of {@link FLNodes }
     * 
     */
    public FLNodes createFLNodes() {
        return new FLNodes();
    }

    /**
     * Create an instance of {@link FLVResults.VResult }
     * 
     */
    public FLVResults.VResult createFLVResultsVResult() {
        return new FLVResults.VResult();
    }

    /**
     * Create an instance of {@link FLNffgs }
     * 
     */
    public FLNffgs createFLNffgs() {
        return new FLNffgs();
    }

    /**
     * Create an instance of {@link FLPolicies }
     * 
     */
    public FLPolicies createFLPolicies() {
        return new FLPolicies();
    }

}
